name: build

on:
  push:
    branches: [master]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v1

    - name: install
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
      run: python -m pip install poetry tox

    - name: build
      run: tox -e build

    - name: publish
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: netlify
        FOLDER: build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
